replicaCount: 1

image:
  repository: floorflow
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 4000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: floorflow.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClass: ""

resources: {}

env: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

admin:
  create: false
  password: ""
  existingSecret: ""
  secretKey: password
